import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "./home.module.css";
import { useCallback, useEffect, useState } from "react";
import { fromFetch } from "rxjs/fetch";
import { from, mergeMap, of } from "rxjs";
import { useRouter } from "next/router";
import {dispatchClick} from "../../store/click/action";
import {useDispatch, useSelector} from "react-redux";
import {selectClickCount, selectClickCountRaisedTo} from "../../store/click/selector";

const Home: NextPage = () => {
  const router = useRouter(); // rooter hook
  const dispatch = useDispatch();
  const clickCountFromStore = useSelector(selectClickCount);
  const clickCountWithParamRaisedTo = useSelector(selectClickCountRaisedTo(clickCountFromStore));
  const [clickCount, setClickCount] = useState<number>(0);

  useEffect(() => {
    fromFetch("http://localhost:3000/api/hello")
      .pipe(
        mergeMap((res: Response) => {
          if (res?.ok) {
            return from(res?.json());
          }
          return of(null);
        })
      )
      .subscribe((res?: any) => {
        console.log(res);
      });
  }, []);

  useEffect(() => {
    console.log("Click count from component state changed: " + clickCount);
  }, [clickCount]);

    useEffect(() => {
        console.log("Click count from store changed: " + clickCountFromStore);
    }, [clickCountFromStore]);

    useEffect(() => {
        console.log("Click count raised changed: " + clickCountWithParamRaisedTo);
    }, [clickCountWithParamRaisedTo]);

  const onWelcomeClick = useCallback((): void => {
      const newCount = clickCount + 1;
      setClickCount(newCount);
      dispatch(dispatchClick(newCount));
  }, [clickCount]);

  const gotoPage = useCallback((page: string) => {
    router?.push(page);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Home Page</h1>
        <Link href="/about">
          <a>About Us</a>
        </Link>
        <span onClick={() => gotoPage("contact")}>Contact</span>
        <p>
          Click <span onClick={onWelcomeClick}>HERE</span>
        </p>
        <p>Number of clicks from component state: {clickCount}</p>
        <p>Number of clicks from redux store: {clickCountFromStore}</p>
        <p>Number of clicks raised to {clickCountFromStore}: {clickCountWithParamRaisedTo}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
